"""add_locations_table_and_fk

Revision ID: 5f24a728d8cc
Revises: 
Create Date: 2026-05-09 10:42:40.007656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f24a728d8cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', name='uq_location_coords')
    )
    op.add_column('forecasts', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_forecasts_city_name'), table_name='forecasts')
    op.create_foreign_key(None, 'forecasts', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_column('forecasts', 'country_code')
    op.drop_column('forecasts', 'longitude')
    op.drop_column('forecasts', 'latitude')
    op.drop_column('forecasts', 'city_name')
    op.add_column('saved_locations', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_user_location'), 'saved_locations', type_='unique')
    op.create_unique_constraint('uq_user_location', 'saved_locations', ['user_id', 'location_id'])
    op.create_foreign_key(None, 'saved_locations', 'locations', ['location_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('saved_locations', 'country_code')
    op.drop_column('saved_locations', 'latitude')
    op.drop_column('saved_locations', 'longitude')
    op.drop_column('saved_locations', 'city_name')
    op.add_column('weather_records', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_weather_records_city_name'), table_name='weather_records')
    op.create_foreign_key(None, 'weather_records', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_column('weather_records', 'country_code')
    op.drop_column('weather_records', 'longitude')
    op.drop_column('weather_records', 'latitude')
    op.drop_column('weather_records', 'city_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_records', sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('weather_records', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_records', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_records', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather_records', type_='foreignkey')
    op.create_index(op.f('ix_weather_records_city_name'), 'weather_records', ['city_name'], unique=False)
    op.drop_column('weather_records', 'location_id')
    op.add_column('saved_locations', sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('saved_locations', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('saved_locations', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('saved_locations', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saved_locations', type_='foreignkey')
    op.drop_constraint('uq_user_location', 'saved_locations', type_='unique')
    op.create_unique_constraint(op.f('uq_user_location'), 'saved_locations', ['user_id', 'latitude', 'longitude'])
    op.drop_column('saved_locations', 'location_id')
    op.add_column('forecasts', sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('forecasts', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('forecasts', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('forecasts', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forecasts', type_='foreignkey')
    op.create_index(op.f('ix_forecasts_city_name'), 'forecasts', ['city_name'], unique=False)
    op.drop_column('forecasts', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
